id: A7B7B3C92
title: Complete text
type: translation
source_metadata:
  languages:
  - fr
  - ug
  - zh
  datatype: PlainText
  created_at: 2022-03-02 09:14:49.989684
  last_modified_at: 2022-03-02 09:14:49.989753
